### PR TITLE
Make Ukrainian names respecting to the Ukrainian laws

### PR DESCRIPTION
**Pull request by podarok**
Good time of the day
According to https://github.com/php/php-src/pull/661 we should make a change here for ability to have proper names for the timezones.

Please review and merge it if everything is ok

### CODE REVIEW

**Comment by opalmirror** [comment]
In http://article.gmane.org/gmane.comp.time.tz/10743, Paul Eggert notes that the TZ Database uses English names, so the English commonly accepted name Kiev is preferred to Kyiv (transliteration of local name). A localization layer may be used to index the local name in local language into the English name used in the Timezone Database (he mentions CLDR).

**Comment by eggert** [comment]
Yes, it appears that the most common spelling in English continues to be "Kiev", despite official governmental preferences for "Kyiv". Although this preference may change eventually, there is no rush to change the tz database, which tends to be conservative about name changes anyway (partly to avoid hassling users with changes that are irrelevant to the primary goal of reporting accurate time stamps). The English-language spelling is not intended to have anything to do with politics, as the vast majority English-speakers don't know about the backgrounds of "Kiev", "Kyiv", "Kyyiv", "Kyjiv", etc.

**Comment by podarok** [comment]
Sorry, guys, but we've started to move *.kiev.ua to *.kyiv.ua and leaving this as is will lead to aggressivenes to you in a future. So if you do not want to help with this, you'll met a lot of issues.

**Comment by eggert** [comment]
There seems to be some misunderstanding of the role of TZ settings. Domain names like *.kyiv.ua interoperate well with TZ settings like Europe/Kiev, just as domain names like *.roma.it interoperate well with TZ settings like Europe/Rome.

TZ settings are not intended for end users. Application developers who prefer other spellings like "Київ" or "Roma" in their user interfaces are encouraged to use CLDR <http://www.unicode.org/cldr/charts/latest/by_type/timezones.europe.html>, which lists localized names for TZ settings. If your user interface does not use CLDR, please file a bug report with its developer; and if CLDR does not list the name appropriate for your locale, please file a CLDR change request <http://cldr.unicode.org/index/bug-reports>.

**Comment by khaiphan9x** [comment]
These are the reasons that I think are reasonable
- After merging with Ha Tay, Hanoi (capital) is the largest province in Vietnam
- +7:00 (North Vietnam and All Vietnam since 1975) timezone has been the longest unified timezone ever, compared to Asia/Saigon, Asia/Ho_Chi_Minh (modified many times)

I would like to suggest adding a timezone for Hanoi or changing the name from Asia/Ho_Chi_Minh to Asia/Hanoi as the official timezone for Vietnam.

Having the same article should be considered
https://tz.iana.narkive.com/foJrvdQn/tz-patch-tzdata-asia-ha-noi-add-new-timezone

**Comment by liuxinyu970226** [comment]
@eggert While I also agree changing the name of Ukrainian capital city should still wait for several years, can we please change Zaporozhye to Zaporizhia first? Because there are also many English-native websites e.g. [English Wikipedia](https://en.wikipedia.org/wiki/Zaporizhia) that adopted this one change.

**Comment by BrianInglis** [comment]
[English Wikipedia](https://en.wikipedia.org/wiki/Zaporizhia) gives three alternative spellings; many more are used on the web, and it is not clear which is the current winner: 
```$ echo Zap{i,o}r{i,o}{zh,zhzh}{ia,ya,ye}``` 
generates all spellings I have seen - two dozen alternatives. 
Should add an alias to Zap, revert to Alexandrovsk, or wait a while longer for consistency to develop.

**Comment by podarok** [comment]
@liuxinyu970226 what are you waiting for?
The more we postpone this, the bigger concerns about community, that supports tz is.
Major players switched to Kyiv already. Opensource has concerns. 
It'll shift to private offense over time because of support from people like you

**Pull request closed without merging**
